config/routes.rb
Rails.application.routes.draw do

  resources :users do
    resources :messages
    resources :friends
  end
  resources :sessions, only: [:new, :create]

  get 'user_home' => 'users#index'
  delete 'logout' => 'sessions#destroy'
  root 'home#index'

end

app/models/friend.rb
class Friend < ActiveRecord::Base
		belongs_to :first_user, class_name: "User"
		belongs_to :second_user, class_name: "User"

		validates :second_user_id, presence: true
end

app/models/message.rb
class Message < ActiveRecord::Base
	belongs_to :sender, class_name: 'User'
	belongs_to :recipient, class_name: 'User'

	validates :title, presence: true
	validates :body, presence: true
	def read?
		# !read_at.nil
		!!read_at
	end
end

app/models/user.rb
class User < ActiveRecord::Base
	has_secure_password

	validates :email, uniqueness: true
	validates :name, presence: true

	has_many :sent_messages, foreign_key: 'sender_id', class_name: 'Message' , dependent: :destroy
	has_many :received_messages, foreign_key: 'recipient_id', class_name: 'Message', dependent: :destroy
	has_many :friends, foreign_key: 'first_user_id', class_name: 'Friend', dependent: :destroy

	# def sent_messages
	# 	Message.where(sender_id: id)
	# end

	# def received_messages
	# 	Message.where(recipient_id: id)
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user

  def current_user
  	return @current_user if @current_user

  	if session[:user_id]
  		@current_user = User.find session[:user_id]
 	end
  end
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
	before_action :require_login

	def new
		init
	end

	def create
		init
		@friend = Friend.new(friend_params)
		@friend.first_user_id = current_user.id
		if @friend.save
			flash[:success] = "Add Friend Successfully"
			second_friend = Friend.create(first_user_id: @friend.second_user_id, second_user_id: @friend.first_user_id)
			redirect_to user_home_path
		else
			flash.now[:error] = "Error: #{@friend.errors.full_messages.to_sentence}"
			render 'new'
		end
	end

	def destroy
		@friendship = current_user.friends.find(params[:id])
		@fromFriend = Friend.find_by(first_user: @friendship.second_user, second_user: @friendship.first_user)

		@friendship.destroy
		@fromFriend.destroy

		flash[:success] = "Successfully destroyed friendship."
		redirect_to user_home_path
	end

	private
	def friend_params
		params.permit(:second_user_id)
	end

	def init
		@user = User.find params[:user_id]
		@users = User.where.not(id: Friend.where(first_user: current_user).pluck(:second_user_id)).where.not(id: current_user.id)
	end

	def require_login
		if !current_user
			flash[:error] = "You must be logged in to access this section"
			redirect_to  new_user_path
		end
	end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	before_action :is_login

	def index
	end

	private
	def is_login
		if !!current_user
			redirect_to user_home_path
		end
	end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
	before_action :require_login

	def new
		init
	end

	def show
		@user = User.find params[:user_id]
		@message = Message.find(params[:id])

		if @message.read?
			redirect_to user_home_path
		else
			@message.read_at = Time.now
			@message.save
		end
	end

	def create
		init
		@message = Message.new(message_params)
		@message.sender_id = current_user.id
		if @message.save
			flash[:success] = "Successfully send the message"
			redirect_to user_home_path
		else
			flash.now[:error] = "Error: #{@message.errors.full_messages.to_sentence}"
			render 'new'
		end
	end

	private
	def message_params
		params.require(:message).permit(:recipient_id, :title, :body)
	end

	def init
		@user = User.find params[:user_id]
		@users = User.where(id: Friend.where(first_user: current_user).pluck(:second_user_id))
	end

	def require_login
		if !current_user
			flash[:error] = "You must be logged in to access this section"
			redirect_to  new_user_path
		end
	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def destroy
	session[:user_id] = nil
	flash[:success] = "Logged out."
	redirect_to root_path
  end

  def create
  	if @user = User.find_by(email: params[:email]) and @user.authenticate(params[:password])
  		session[:user_id] = @user.id
  		redirect_to user_home_path
  	else
  		flash.now[:error] = "Invalid User"
  		render 'new'
  	end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :require_login, except: [:new, :create]

	def index
		@received_messages = current_user.received_messages.page(params[:page]).order(created_at: :desc).per(10)
		@sent_messages = current_user.sent_messages.page(params[:page]).order(created_at: :desc).per(10);
	end

	def new
		@user = User.new
	end

	def create
		@user = User.create user_params

		if @user.save
		# if @user.persisted?
		session[:user_id] = @user.id
		flash[:success] = "Registed Success"
		redirect_to user_home_path
	else
		flash.now[:error] = "Error: #{@user.errors.full_messages.to_sentence}"
		render 'new'
	end
end

private
def user_params
	params.require(:user).permit(:name, :email, :password, :password_confirmation)
end

def require_login
	if !current_user
		flash[:error] = "You must be logged in to access this section"
		redirect_to  new_user_path
	end
end
end

app/helpers/application_helper.rb
module ApplicationHelper


end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
	def flash_class_name(key)
		case key.to_s
		when "success"
			"alert-success"
		when "error"
			"alert-danger"
		else
			"alert-warning"
		end
	end
end

app/views/friends/new.html.erb
<% if !@users.blank? %>
<%= form_for [@user, Friend.new] do |f| %>
<table>
	<tr>
		<td><%= f.label "Add as friend: " %></td>
		<td><%= select_tag "second_user_id", options_from_collection_for_select(@users, "id", "name") %></td>
	</tr>
</table>
<%= f.submit "Add Friend"%>
<% end %>
<% else %>
<h1>You are everyone's friend</h1>

<% end %>

app/views/home/index.html.erb
<div class="jumbotron">
	<h1 class="display-3">Welcome to WhatMessage</h1>
	<p class="lead">Want to send a message that can only be read by your friend? This is the place.</p>
	<p class="lead">
		<%= link_to "Join Us", new_user_path, class: "btn btn-primary" %>
		<%= link_to "Log in",  new_session_path, class: "btn btn-primary" %>
	</p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>WhatMessage</title>
	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	<%= csrf_meta_tags %>
</head>
<body>
	<div class="alert alert-info" style="overflow: hidden">
		<% if current_user %>
		<div class="navbar-icons">
			<%= link_to "Home", user_home_path  %>
		</div>

		<div class="user-info">
			Welcome, <%= current_user.name %>
			<%= link_to "Log out", logout_path, method: "delete"  %>
		</div>
		<% else %>

		<div class="navbar-icons">
			<%= link_to "Home", root_path  %>
		</div>

		<div class="user-info">
			<%= link_to "Register", new_user_path %>
			<%= link_to "Log in",  new_session_path %>
		</div>
		<% end %>
	</div>

	<% if flash.any? %>
	<% flash.each do |key, value| %>
	<div class="alert <%= flash_class_name(key) %>"> <%= value %></div>
	<% end %>
	<% end %>

	<div class="container">
		<%= yield %>
	</div>

</body>
</html>

app/views/messages/new.html.erb
<% if !@users.blank? %>
<%= form_for [@user, Message.new] do |f| %>
<table>
	<tr>
		<td><%= f.label "To: " %></td>
		<td><%= f.collection_select(:recipient_id, @users, :id, :name) %></td>
	</tr>
	<tr>
		<td><%= f.label :title %></td>
		<td><%= f.text_field :title %></td>
	</tr>
	<tr>
		<td><%= f.label :boby %>	</td>
		<td><%= f.text_area :body %></td>
	</tr>
</table>
<%= f.submit %>
<% end %>
<% else %>
You have no one to send message to.
<br>
<%= link_to "Add New Friend", new_user_friend_path(current_user.id), class: "btn btn-secondary"%>
<%= link_to "Back",  user_home_path, class: "btn btn-secondary"%>
<% end %>

app/views/messages/show.html.erb
<div class="card">
	<div class="card-header">
		<h4 class="card-title title-custom"><%= @message.title %></h4>
	</div>
	<div class="card-block">
		<p class="card-text">From: <b><%= @message.recipient.name %></b></p>
		<p class="card-text"><%= @message.body %></p>
		<p class="card-text"><%= @message.created_at %></p>
	</div>

	<div class="card-footer text-muted">
		You won't be able to read this message again once you return.
		<%= link_to "Back", user_home_path %>
	</div>
</div>

app/views/users/index.html.erb
 <div class="row">
 	<div class="col-sm-2 user-selection" style="margin-right: 10px">
 		<%= link_to "Compose", new_user_message_path(current_user.id), class: "btn btn-secondary user-btn", style: "margin-top: 10px"%>
 		<div class="btn btn-primary user-btn" id="inbox-btn">Inbox</div>
 		<div class="btn btn-secondary user-btn" id="send-mess-btn" >Sent Message</div>
 		<%= link_to "Add Friend", new_user_friend_path(current_user.id), class: "btn btn-secondary user-btn", style: "margin-top: 20px" %>
 		<div class="btn btn-secondary user-btn" id="friend-list-btn" style="margin-bottom: 10px">Friend List</div>

 	</div>

 	<div class="col-sm-8 mail-list" id="sent-div">
 		<% if  !@received_messages.blank?  %>
 		<div class="row">
 			<% @received_messages.each do |m| %>
 			<div class="<%= cycle('even', 'odd', name:"No") %>">
 				<div class="col-sm-5 row-color">
 					<% if !m.read? %>
 					<b><%= link_to m.title, user_message_path(current_user.id, m.id)%> </b>
 					<% else %>
 					<%= m.title %>
 					<% end %>
 				</div>
 				<div class="col-sm-3 row-color"><i>From: <%= m.sender.name %></i></div>
 				<div class="col-sm-4 row-color"><b>At: <%= m.created_at %></b></div>
 			</div>
 			<% end %>
 			<% reset_cycle("No") %>
 			<%= paginate @received_messages %>
 		</div>
 		<% else %>
 		<h1>Inbox empty</h1>
 		<% end %>
 	</div>

 	<div class="col-sm-8 mail-list hidden" id="received-div">
 		<% if  !@sent_messages.blank?  %>
 		<div class="row">
 			<% @sent_messages.each do |m| %>
 			<div class="<%= cycle('even', 'odd', name:"No") %>">
 				<div class="col-sm-5 row-color">
 					<%= m.title %>
 				</div>
 				<div class="col-sm-3 row-color"><i>To: <%= m.recipient.name %></i></div>
 				<% if m.read? %>
 				<div class="col-sm-4 row-color"><b>Read At: <%= m.read_at %></b></div>
 				<% else %>
 				<div class="col-sm-4 row-color"><b>Read At: Unread</b></div>
 				<% end %>
 			</div>
 			<% end %>
 			<% reset_cycle("No") %>
 			<%= paginate @sent_messages %>
 		</div>
 		<% else %>
 		<h1>You haven't sent any email</h1>
 		<% end %>
 	</div>

 	<div class="col-sm-8 mail-list hidden" id="friend-div">
 		<% if !current_user.friends.blank? %>
 		<ul class="ul-friend">
 			<% current_user.friends.each do |f| %>
 			<li class="<%= cycle('even', 'odd-friend', name:"No")%> col-color">
 				<%= f.second_user.name %> : <%= f.second_user.email %> <%= link_to "Delete",  user_friend_path(current_user.id,f.id), :method => :delete %>
 			</li>
 			<% end %>
 		</ul>
 		<% reset_cycle("No") %>
 		<% else %>
 		<h1>You also have no friend</h1>
 		<% end %>
 	</div>
 </div>

app/views/users/new.html.erb
<h1>Sign up</h1>

<%= form_for(@user) do |f| %>
<table>
	<tr>
		<td><%= f.label :name %></td>
		<td><%= f.text_field :name %></td>
	</tr>
	<tr>
		<td>	<%= f.label :email %></td>
		<td>	<%= f.text_field :email %></td>
	</tr>
	<tr>
		<td>	<%= f.label :password %>
		</td>
		<td>	<%= f.password_field :password %>
		</td>
	</tr>
</table>
<%= f.submit %>
<% end %>